### ISSUE TITLE
Flatpak Broken Package Check

### ISSUE THREAD

**Issue by brent111** [getsolus/packages#1035]
### Summary

was asked by Tracy at forum to report this bug. it's pretty harmless.
```
sudo eopkg check flatpak
Checking integrity of flatpak    Broken
Corrupted file: /usr/lib/tmpfiles.d/flatpak.conf
```
I say it's harmless because I was able search and install with flatpak. Maybe it's something benign?

### Steps to reproduce

1) `sudo eopkg check flatpak`

### Expected result

`Checking integrity of flatpak    OK`

### Actual result

```
Checking integrity of flatpak    Broken
Corrupted file: /usr/lib/tmpfiles.d/flatpak.conf
```

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

budgie, solus, 10.8.2
updated the night of 12/15/2023
woke up, rebooted, and filing this report the morning of 12/16/2023

### Other comments

 a full `eopkg check` revealed, for me, this was the only broken package

**Comment by brent111** [comment]
forgot to add a handful of people who updated did corroborate this, too. see last 10 posts or so https://discuss.getsol.us/d/10070-sync-updates-for-week-50-2023/9

**Comment by Staudey** [comment]
That's because [flatpak now includes its own tmpfiles.d config](https://github.com/flatpak/flatpak/pull/5584), while our [package recipe has a custom config from way back when](https://github.com/getsolus/packages/blob/main/packages/f/flatpak/files/flatpak.tmpfiles). The former copies to `/usr/lib/tmpfiles.d/` and gets recorded in the package metadata, while the latter copies to `/usr/lib64/tmpfiles.d/`, also recorded in the metadata. That ends up being the same location though, and only the latter remains on a real installation.
