### ISSUE TITLE
Solus 4.5 - Calamares swap to file hibernation is broken

### ISSUE THREAD

**Issue by HarveyDevel** [getsolus/packages#1077]
### Summary

Calamres has swap options:
No Swap || Swap (no Hibernate) || Swap (with hibernate) || Swap to file 

Swap to file will not be able to hibernate as it will be too small and increasing its size relative to the amount of RAM takes too long (more than a minute). 

Suggestion:
Make swap to file -> swap to file (no hibernate) or disable swap to file, 512MB is way too small.

### Steps to reproduce

N/A

### Expected result

Knowing if hibernate will work before you install.

### Actual result

Hibernate does not work without user recreating swapfile.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

N/A

**Comment by HarveyDevel** [comment]
Alternatively we could improve swap file creation. Make it a reasonable size very quickly using fallocate (8GB swap created instantaneously in testing)

Example of usage in the wild with ext4:
https://github.com/linuxmint/ubiquity/blob/256b2a65837d03654e91fdaaa875f36a252d0ba1/d-i/source/partman-swapfile/finish.d/create_swapfile#L38 

f2fs also  support it:
https://github.com/torvalds/linux/blob/master/Documentation/filesystems/f2fs.rst 

it should be disabled on BTRFS because its a bit more complicated:
https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#swapfile-support

**Comment by silkeh** [comment]
> it should be disabled on BTRFS because its a bit more complicated and has caveats:

For Btrfs the process should be something like:

```console
btrfs sub cr /swap
btrfs filesystem mkswapfile --size=4G /swap/swapfile
```

Which is also very fast. More info can be found in [the Btrfs docs on swapfiles](https://btrfs.readthedocs.io/en/latest/Swapfile.html).

**Comment by WetGeek** [comment]
In #1014, I describe a problem I've run into in which Xfce won't successfully restore a session after hibernation.  This is on a laptop that has 16 GB of RAM and has a 24 GiB swap partition.  It goes through the motions when told to hibernate, but when the system is restarted the previous session isn't restored.  This issue implies that if I were to create a swap file instead of a swap partition, it would successfully restore a session upon restarting--is that true?  If so, I'll add that comment to #1014, although I'll leave it open.  Hibernation _should_ still work with the setup I described.

**Comment by ermo** [comment]
> Alternatively we could improve swap file creation.

I think that, for 4.5, we can just disable the swap file option.

For 4.6, we can think about upstreaming patches that improve on the functionality that currently doesn't quite work?
