### ISSUE TITLE
Trim does not work with LUKS encrypted drive

### ISSUE THREAD

**Issue by riffer33** [getsolus/packages#1240]
### Summary

systemctl status fstrim returns:
○ fstrim.service - Discard unused blocks on filesystems from /etc/fstab
     Loaded: loaded (/usr/lib/systemd/system/fstrim.service; static)
    Drop-In: /usr/lib64/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
TriggeredBy: ● fstrim.timer
       Docs: man:fstrim(8)
After install.

Running sudo fstrim -a -v etc returns nothing indicating command is not working.

### Steps to reproduce

sudo fstrim -a -v
or
sudo fstrim -av
return nothing

### Expected result

Some message relating to what has been trimmed etc.

### Actual result

No message.  Returns to prompt.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Gnome

### System details

# System Details Report
---

## Report details
- **Date generated:**                              2024-01-09 17:33:09

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad X1 Carbon Gen 8
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-10510U × 8
- **Graphics:**                                    Intel® UHD Graphics (CML GT2)
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            N2WET43W (1.33 )
- **OS Name:**                                     Solus 4.5 Resilience
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.9-269.current

### Other comments

I've managed to piece together a solution, but I don't really know what I am doing :)  I would prefer it worked out of the box.  Thanks

edit etc/lvm/lvm.conf
issue_discards = 1
Move to this directory | cd /etc/kernel
sudo su
sudo echo "rd.luks.options=discard" > /etc/kernel/cmdline
exit
Test
cat cmdline
sudo clr-boot-manager update
sudo eopkg install dracut
sudo dracut --force
reboot

**Comment by riffer33** [comment]
Edit:  Corrected DE from Budgie to Gnome

**Comment by ReillyBrogan** [comment]
This appears to be upstream behavior. The references I have read say that the dm-crypt developers (the tech behind LUKS) have no intention of ever enabling TRIM by default since it can be a security risk (leaks information about the blocks being freed). I don't really see a reason to override their default, if running TRIM is important to you then you'll need to enable it manually.

That said, I do think there's room for enhancing our help documentation to cover how to best enable this on Solus. If you or someone else would like to create a PR for our help docs (https://github.com/getsolus/help-center-docs) I'll gladly review it.
