### ISSUE TITLE
Deprecate Kodi

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1313]
Deprecate the Kodi package. It has a high maintenance burden.

**Comment by davidjharder** [comment]
Tangentially related: https://github.com/getsolus/help-center-docs/issues/460

**Comment by ermo** [comment]
@nazar-stasiv Just bringing this to your attention:

The issue with having this package as-is in the repo (which I we deprecated once already, due to the reasons I'm about to outline) is as follows:

- We're using an unsupported method of building the package (the method we use is only supported by upstream for local builds)
- We have no control over, nor insight into, which of the dependencies in the package are built correctly (apart from inspecting the build log) as the build will not fail if one of the git subtree dependencies fail to build.
- As a result of how the build works, this means that builds are not reproducible even when using an unchanged kodi git tag

Originally, this package was brought back to life _after being deprecated for the exact same reasons as outlined above_ with just a small set of binary add-ons (and even then, it was not the ideal outcome).

With the full fat build we have today -- with the issues outlined above -- we might as well point people towards the Flatpak version of Kodi.

As it stands, we therefore intend to deprecate Kodi from the repo at some point soon.

**Comment by nazar-stasiv** [comment]
I'm aware about future Solus 5.0 not shipping Kodi anymore. Also good luck with the 5.0.

**Comment by ermo** [comment]
> I'm aware about future Solus 5.0 not shipping Kodi anymore. Also good luck with the 5.0.

@nazar-stasiv : It's actually going to be deprecated sooner than 5.0 probably; currently, it's on the chopping block for the near future.

Having previously maintained Kodi (and being the person who came up with the current "clever" build hack), I _know_ it's not your fault that Kodi binary add-ons randomly stop working; it's simply an artefact of the build process being, well, as I said: A hack to save time.

So Solus wanting to deprecate Kodi from the repo has nothing to do with the job you've done in terms of building and maintaining it. I hope you understand that. :sweat_smile:
