### ISSUE TITLE
Enable faster-than-sha1 build ids in LLVM, mold and binutils

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#1346]
XXH3_64 bit is much faster than SHA-1.

EDIT:
- Reilly is of the opinion that XXH3_64 bit gives too high probability of collisions, so this is a no-go
- BLAKE3 support (with hash truncated to 160 bits / 20 bytes) is supported with getsolus/packages#4570 and getsolus/packages#4575 for the relevant packages
- XXH3_128 bit is in the works for binutils upstream (binutils is where it'll give the largest speedup according to Reilly, see his comment below)

**Comment by ReillyBrogan** [comment]
Any objection to changing this to "Enable BLAKE3 for build IDs in LLVM/MOLD/binutils"?

If that's fine then this can be marked as complete once getsolus/packages#4570 and getsolus/packages#4575 land. MOLD was done in 61a0bae3effcc0fa708f6d1d733577fb3d951447

We can revisit XXH3 when support for it lands in a released version of binutils. My gut feeling is that we're getting 90-95% of the possible improvement of SHA1 -> XXH3 by using BLAKE3 and it might not be worth pursuing. If it's worth doing anywhere though it'll be binutils since the hashing there does the entire buffer in one thread. LLVM/MOLD are likely to not see as much improvement since they break the input into 1MB chunks and do them in parallel.

**Comment by ermo** [comment]
Closing this as the scope of "faster build id generation" has now been achieved.

getsolus/packages#4603 is for tracking whether the next frontier of performance is worth pursuing.
