### ISSUE TITLE
Installation fails on systems with existing EFI partition that is less than 1G unless user selects CSM

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1350]
### Summary

When installing Solus alongside another OS, if the EFI partition is less than 1G, the user will get an error. By default all other OSs create an EFI partition between 100 - 512 MB.

There's a list of [default EFI partition sizes on this blog post](https://www.ctrl.blog/entry/esp-size-guide.html) 
Solus is always going to require more than what is available on a default existing install, and will therefore always fail to install alongside another OS.

### Steps to reproduce

1. Have a system with another OS installed and an EFI partition < 1G (An Ubuntu 22.x install creates an EFI partition of 512MB)
2. Run the Solus 4.5 installer from a live USB disk
3. Select the option to install Solus alongside the other OS(s)

### Expected result

Install is successful

### Actual result

Installation fails with an error

> The bootloader could not be installed. The installation command ‹pre›cr-boot-manager update</pre> returned error code 1.

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Other

### System details

User's system in forum thread:

>I tried to install Solus 4.5 on a SSD with a UEFI Windows 10 Dual Boot 
> I have two 16gb sandisk flash drives and prepared one Solus 4.5 Budgie.iso on Windows with Balena Etcher and other one on Fedora(Another computer) with Fedora Media Writer 
> I was able to install it selecting CSM but i dont wish to use it like that as it requires me to change it on Bios on which OS to boot. Tried with Secure boot enabled/disabled to no avail. I used to have EndeavourOS installed on it but Brute force deleted it from Windows side. Maybe it messed something up?

### Other comments

Error affected a user who reported it in [this forum thread](https://discuss.getsol.us/d/10162-bootloader-installation-error)

- Installer could allow the option to opt into resizing the EFI partition (with warnings as appropriate about potential data loss)  If the user opts out, provide a message about the minimum EFI disk requirement and provide guidelines on how to resize it
- The error message is pretty opaque and could be improved

Note: CSM is "Compatibility Support Module" or "Legacy BIOS support", which ignores EFI which is why that would not trigger the error.

**Comment by TraceyC77** [comment]
I'm going to investigate this on a Windows 11 VM

**Comment by sebo505** [comment]
On the same matter: we recently had support requests on the matrix channels for people with failing installations.
During boot loader installation, they got error: `The bootloader could not be installed. The installation command <pre>clr-bbot-manager update</pre> returned error code 1.`
They then tried to install several times, getting same error every time. And off course they could not understand what excactly the problem was.
Tracey then explained that this error usually means that the boot /uefi partition is less than 1g and that the error message might not state this clearly probably due to a Calamares limitation.
If that is the case, I would suggest to at least run a check for uefi partition size when clicking on the installer and popping up a notification if uefi partition is to small.
This might reduce at the same time frustrations for new Solus users whose installations fail without that they can clearly understand why and subsequently support burden.
