### ISSUE TITLE
Hyprland

### ISSUE THREAD

**Issue by yusi1** [getsolus/packages#1362]
### Homepage

https://hyprland.org

### Why should this be included in the repository?

It is a Wayland based tiling window manager that looks nice and is based on modern technologies.

### Are we allowed to redistribute it?

BSD

### What kind of user will use this package, and how many users do you think will use this package?

Any user

### Link to source archive file

https://github.com/hyprwm/Hyprland/releases/download/v0.34.0/source-v0.34.0.tar.gz

**Comment by ReillyBrogan** [comment]
Due to the effort involved in maintaining something like this whoever is interested will need to reach out to Solus staff on the Packaging or Devel channels on our Matrix. We're mostly looking for experienced packagers who understand that that things like this require a lot more work than most packages and are willing to commit to that work. 

It would also be possible (and even desired) for multiple individuals to come together to form a "Hyprland tribe" willing to maintain it on Solus. That would spread out the maintenance burden quite substantially and would mean that if one maintainer left that we didn't lose all of their knowledge on how to best maintain it going forward.

So I'm going to mark this as approved, but please note that it's approved conditionally and PRs for it **WILL BE REJECTED** if they are submitted without reaching out to us on Matrix first.

**Comment by davidjharder** [comment]
Conditionally Approved, see Reilly's comment

**Comment by Justinzobel** [comment]
It also requires an in-package build of wlroots as they depend on git master commits, not tagged releases.

**Comment by ReillyBrogan** [comment]
@yusi1 If you're still interested in working on this we could put a call for contributors post on the forum. If we can get ~2 more interested folk to help maintain/update this then that would be sufficient for me.

**Comment by EbonJaeger** [comment]
It looks like the developers want to move away from an Open Source license. While it hasn't happened yet, [it looks like their minds are made up](https://github.com/hyprwm/Hyprland/pull/4915). I'm not sure that we want to accept this for inclusion, as distributing it might be dubious.

**Comment by TraceyC77** [comment]
At the very least, we need to wait until they decide on their new licensing to see if we could legally distribute it.

**Comment by Staudey** [comment]
Well, the code is permissively licensed as it stands right now, and from the discussion it seems like they underestimated how easily they could lock things down. Last comment from the main dev is that they'll talk to a lawyer "this summer", so it'll be a while before any changes will take place (if they ever do).
In any case distributing the current version of it, and any that get released until a license change takes place, is perfectly fine.

That being said it would be annoying if they actually end up relicensing in a way that prohibits redistribution by Solus, in which case we couldn't update it any longer (though it does not seem like that is their intention)

**Comment by Justinzobel** [comment]
I imagine if it does go closed source, someone will fork it, which I hope is what happens.

**Comment by yusi1** [comment]
> @yusi1 If you're still interested in working on this we could put a call for contributors post on the forum. If we can get ~2 more interested folk to help maintain/update this then that would be sufficient for me.

Yes I can help with this if you guys are in need of help.

**Comment by Smokolak** [comment]
> Hello everyone
> 
> Would someone be willing to become a maintainer for Hyprland packages with me. I have already built and tested them with a second person (everything is ok for now).
> 
> One of the conditions being to be several maintainers for the validation of the packages, I try my luck here :)
> 
> You can find me on the Solus Matrix as genick, or on the Solus forum as gNick

Hey mate, I'm @bialy_wilk from Matrix, I will be happy to help with it. 
Tested your packages:
- [ ] fresh install of Solus Gnome on Ryzen3600x + Gpu rx570 - installed packages - all fine
- [ ] fresh install of Solus Gnome in VM + build packages with @gNick ymls and installed in local repo - all fine
- [ ] fresh install of Solus Plasma in VM - installed packages - all fine
