### ISSUE TITLE
MakeMKV

### ISSUE THREAD

**Issue by codewizard1975** [getsolus/packages#1420]
### Homepage

https://makemkv.com

### Why should this be included in the repository?

It allows for ripping of DVDs and Blurays to the hard drive.

Linux version forum link: https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224

### Are we allowed to redistribute it?

GPL-2.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

Anyone who wishes to archive or manage their video library.

### Link to source archive file

https://www.makemkv.com/download/makemkv-bin-1.17.6.tar.gz

**Comment by HarveyDevel** [comment]
It is not GPL it is proprietary.

We used to have it in the repository but it was deprecated due to user complaints / confusion surrounding the need for a license key that expires every month or so. It also had a history blocking ffmpeg updates due to slow development and as such will not be returning to the repository.

There is a flatpak for it that I am informed works well. https://flathub.org/apps/com.makemkv.MakeMKV

**Comment by codewizard1975** [comment]
Thank you for the details.
