### ISSUE TITLE
InputAdaptive addon for Kodi is gone after update

### ISSUE THREAD

**Issue by Solarunit** [getsolus/packages#1441]
### Summary

InputAdaptive addon for Kodi is gone after update

### Steps to reproduce

1. go to My addons > VideoPlayer InputStream
2. InputAdaptive is missing

### Expected result

InputAdaptive addon should be installed

### Actual result

InputAdaptive addon is missing

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Solus Budgie :heart:

### Other comments

on Arch (btw) InputAdaptive addon comes as separate package

**Comment by ermo** [comment]
This is a known issue.

I would recommend that you begin considering using the flatpak version instead, as the way we currently build kodi is ... _unreliable_ to put it mildly.

(FWIW, I have already gotten Kodi deprecated once due to how ... "interesting" it is to maintain)

**Comment by Solarunit** [comment]
I have Kodi flatpak installed too. I use "system" version because flatpak version has limitation like ability to use external player.

**Comment by nazar-stasiv** [comment]
Many more plugins are  missing in https://github.com/getsolus/packages/commit/6fd8535f04040106df80225533d6023d5677c7b3

**Comment by ReillyBrogan** [comment]
This is unlikely to be resolved frankly. Many plugins don't build with GCC 13 however instead of failing the build script just silently skips them. It does not appear to be feasible to patch the failing plugins due to the way the build is structured.

For a while we had GCC 12 packaged SOLELY for Kodi, however with the FFMPEG 6.1 rebuilds it became necessary to use the internal FFMPEG build which does not build with GCC 12, so that had to be reverted.

Considering the impossibility of effectively maintaining the Kodi package it has been deemed acceptable by Solus staff for the binary addons to be allowed to fail to build. We'll only ensure that the core Kodi build succeeds and any binary addons that build are considered bonus. The only alternative would be to hold back major stack upgrades purely for a minority of users who refuse to use the well-supported Flatpak which is not an acceptable alternative.

**Comment by Solarunit** [comment]
What about other alternative for just InputAdaptive addon? Moving it into a separate package like Arch does it?

**Comment by nazar-stasiv** [comment]
> This is unlikely to be resolved frankly. Many plugins don't build with GCC 13 however instead of failing the build script just silently skips them. It does not appear to be feasible to patch the failing plugins due to the way the build is structured.
> 
> For a while we had GCC 12 packaged SOLELY for Kodi, however with the FFMPEG 6.1 rebuilds it became necessary to use the internal FFMPEG build which does not build with GCC 12, so that had to be reverted.
> 
> Considering the impossibility of effectively maintaining the Kodi package it has been deemed acceptable by Solus staff for the binary addons to be allowed to fail to build. We'll only ensure that the core Kodi build succeeds and any binary addons that build are considered bonus. The only alternative would be to hold back major stack upgrades purely for a minority of users who refuse to use the well-supported Flatpak which is not an acceptable alternative.
> 

Thanks for the extended comment.
