### ISSUE TITLE
Update sunshine to 0.21.0 (T10498)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#155]
<div dir="rtl"><b>Roice&nbsp;Young</b>&nbsp;(<em>&#35;DekoDx</em>),&nbsp;2023-04-27&nbsp;23:31:26&nbsp;UTC</div><br/>

fixes bugs and adds new features

https://github.com/LizardByte/Sunshine/releases/tag/v0.19.1

**Comment by ReenigneArcher** [comment]
Now, v0.21.0, and I'm planning to release v0.22.0 soon.

The version you provide is VULNERABLE to security issues. You are putting your users at risk by not updating.

**Comment by ReillyBrogan** [comment]
> The version you provide is VULNERABLE to security issues. You are putting your users at risk by not updating.

@ReenigneArcher Do you have a CVE for the issue for reference?

**Comment by joebonrichie** [comment]
I updated the package to bring it up to date but we'll need a dedicated maintainer for this package going forward otherwise it'll be deprecated in favor of the flatpak.

**Comment by ReenigneArcher** [comment]
@ReillyBrogan sorry, no CVEs.

See here though.

https://github.com/LizardByte/Sunshine/releases/tag/v0.18.0

It is intentionally vague as to not provide required details to attackers... but the software is open source, so probably not that difficult to figure out.

**Comment by ReillyBrogan** [comment]
@ReenigneArcher I found the PR, am I correct in my assessment that the vulnerability allows anyone with access to the webUI to read arbitrary files on the host system? And that this appears to happen prior to an authentication phase? If so frankly you should be requesting a CVE for this and publicizing it. Considering that the fix (and the vulnerability by analysis) has already been publicly visible for almost a year now it is an almost certainty that attackers are already aware of it (they constantly scan github for things like this) it's probably already being actively exploited. The responsible thing at this point would be to try to publicize it as much as possible so that users running things like docker containers that aren't automatically updated can be notified and take corrective action.

You should request a CVE via MITRE via [this form letter](https://cveform.mitre.org/). I would also highly recommend sending an email to the `oss-security` mailing list, the process for that is available [here](https://oss-security.openwall.org/wiki/mailing-lists/oss-security).

**Comment by ReenigneArcher** [comment]
I've submitted a CVE request. In the meantime, it might be good to remove your comment with these details.

Also, please understand Sunshine is maintained by a very small team of ~3 regular volunteers. Back then it was even fewer regulars. Security issues are bound to sneak in from time to time. We do have CodeQL scanning now, but I don't think it would have even caught this... maybe in a Python application, but I doubt it would in c++.

**Comment by ReenigneArcher** [comment]
@ReillyBrogan MITRE never issued me a CVE. I ended up requesting it through GitHub's security feature instead and it was issued within a few hours.

https://github.com/LizardByte/Sunshine/security/advisories/GHSA-6rg7-7m3w-w5wc
