### ISSUE TITLE
melonDS

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1749]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://melonds.kuribo64.net/

### Maintainer

- [x] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

We don't have a dedicated Nintendo DS emulator in repo. As always, I already have working recipe.

### Are we allowed to redistribute it?

GPL-3.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

Retro(?) games enthusiast

### Link to source archive file

https://github.com/melonDS-emu/melonDS/archive/refs/tags/0.9.5.tar.gz

**Comment by infinitymdm** [comment]
Out of curiosity, what made you choose melonDS over the other DS emulators out there?

**Comment by malfisya** [comment]
The only open-source one? I used Desmume and No$GBA back in the day, but those aren't open-source, right? So far melonDS has been okay. Do tell me your opinion of NDS emulators.

**Comment by malfisya** [comment]
TIL desmume is indeed open-source https://github.com/TASEmulators/desmume/releases/tag/release_0_9_13🙃

**Comment by infinitymdm** [comment]
To be honest, I don't usually use a separate NDS emulator. I just use Retroarch. I don't recall which core I've used - probably worth checking. (Then again, I don't play NDS games very often, so :man_shrugging: )

Would you be willing to share your package.yml for melonDS? I'd be interested in comparing features to see what melonDS gets us vs other alternatives. I'd also be glad to help test this package (or alternative DS emulators) with the handful of games that I have.

**Comment by malfisya** [comment]
Here you go https://github.com/malfisya/packages/tree/melonds/packages/m/melonds . I will also try build desmume tomorrow. Cheers!

**Comment by malfisya** [comment]
desmume : https://github.com/malfisya/packages/tree/melonds/packages/d/desmume

**Comment by infinitymdm** [comment]
Thanks for putting both packages together! I've messed around with both a bit by this point, using a handful of games from various franchises (Pokemon, Mario 64, Starfy, Kirby, Mariokart).

I've been pleasantly surprised with melonDS - it seems to have a lot more graphical options than Desmume, while also being laid out a bit more intuitively and feeling more "native" to Linux. Desmume definitely gives off a "Linux is not our primary target" vibe. Honestly, I was expecting Desmume to be the clear winner here, but I think I was misremembering/confusing some of its features with Citra. Maybe Desmume has a few more debug/homebrew options, but otherwise I'm sold on melonDS.

There are a few features I'd still like to make sure are working - namely wireless multiplayer and microphone - but so far melonDS seems like the way to go IMO. It's also roughly half the size of Desmume (not that either app is huge, but it helps).

Thanks again for your work here!

**Comment by malfisya** [comment]
As much as I like using emulators, I rarely dig into the settings. As long as the game runs, it satisfies me. So, thank you for getting deep into this. 
So here is my surface opinion on Desmume and melonDS. As a gnome plebs, I am quite pleased that Desmume is using gtk, It blends with my other app. Still look quite dated though with menu bar and all. MelonDS using Qt makes it not blend well, and with me using Kvantum theme (My fault) worsen it. Some button portion of the window is not visible. 
The setting menu I use is only the controller setting. MelonDS is clear winner here. With controller diagram laid out instead of only a list of button name on Desmume. 
By default, it seems audio is more crisp on Desmume than on melonDS (Surely can be tweaked in settings). 
Performance wise, I couldn't tell a difference. So, my conclusion is the same as you. MelonDS is the way to go. Unless you find some more info to consider. I hope this package request can get approved. Cheers!
