### ISSUE TITLE
List of my unwatched packages (T10538)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#176]
<div dir="rtl"><b>Maik&nbsp;Wöhl</b>&nbsp;(<em>@maikwoehl</em>),&nbsp;2023-05-21&nbsp;20:58:24&nbsp;UTC</div><br/>

Hello lovely solus community,

as I already communicated on matrix SolusDev channel, I will not be able to watch the following packages over the course of the next months. 

I expect to sort everything out until christmas this year (2023). Let me know on matrix (@maikwoehl:matrix.org) whether informations or updates are needed and I check whether I have the spare time to update.

You can put all packages on "Need maintainer" immediately or wait until 2024. I will accept either one of the decisions of the solus team.

The musescore update to 4.x will be delivered next weekend. D13905

```
flask-socketio
horizon-eda
musescore
onionshare
onionshare-cli
openpaperwork-core
openpaperwork-gtk
paperwork
paperwork-backend
paperwork-shell
python-bidict
python-cepa
python-engineio
python-eventlet
python-fabulous
python-getkey
python-gevent
python-gevent-websocket
python-qrcode
python-socketio
```

I wish you all the very best,

Maik

**Comment by maikwoehl** [comment]
I would suggest deprecating `onionshare` as a package in the repo completely. Due to it's big dependency stack it is a lot of work for a package that can be installed with flatpak or snap.

```
$ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
$ flatpak install flathub org.onionshare.OnionShare
```
```
sudo snap install onionshare
```

For `onionshare-cli` we brought in the following packages:

- onionshare-cli
  - ~python-getkey~ _(already deprecated)_
  - python-cepa
  - python-eventlet
  - python-gevent-websocket
    - python-gevent
  - python-flask-socketio
    - python-socketio
      - python-bidict

For `onionshare` the package `python-qrcode` was brought in, but is now also used by `gajim`.

What do you think?

**Comment by Justinzobel** [comment]
@maikwoehl are you back and happy to continue to maintain this?

**Comment by maikwoehl** [comment]
I'm ready to take maintainership again.

It may be that I will drop onionshare nontheless, but we will so how it goes.
