### ISSUE TITLE
pre-commit-hooks: package_checks.py has no output

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1991]
When package_checks.py ran for [pr 1783](https://github.com/getsolus/packages/actions/runs/8459375383/job/23175579032?pr=1783) the error text was blank.

It should produce the reason the check failed.

![image](https://github.com/getsolus/packages/assets/10402612/c9db8b06-611a-4077-86b5-ef4146fb2a93)

The problems found in the PR:

Check warning on line 26 in packages/l/libTAS/package.yml
rundeps are not in order

Check warning on line 1 in packages/l/lua53/package.yml
Package release is not 1

Check warning on line 1 in packages/s/suricata/package.yml
Package release is not incremented by 1

 Check warning on line 12 in packages/v/vim/package.yml
builddeps are not in order

Check warning on line 1 in packages/v/vlc/package.yml
Package release is not incremented by 1

**Comment by ermo** [comment]
@TraceyC77 Is this still an issue? I think Silke reworked this recently...

**Comment by TraceyC77** [comment]
I re-tested by intentionally changing the builddeps of syncthing to be incorrect, as well as making sure the release was not incremented, and submitting [this PR](https://github.com/getsolus/packages/pull/2685)

Nothing has changed. The error is still blank.

**Comment by silkeh** [comment]
I've been struggling to reproduce this (see [here](https://github.com/silkeh/packages/pull/9/checks)), but I can't. Turns out that I don't actually see the issue in the mentioned workflow runs either:

[Syncthing PR](https://github.com/getsolus/packages/actions/runs/9215821699/job/25354906470):
<details>
<summary>Screenshot</summary>
<img src="https://github.com/getsolus/packages/assets/5798032/1aa6eee4-9ff3-48e2-a51c-c128e470aa88"/>
</details>

[Lua PR](https://github.com/getsolus/packages/actions/runs/8459375383/job/23175579032):

<details>
<summary>Screenshot</summary>
<img src="https://github.com/getsolus/packages/assets/5798032/8d9b4665-1a79-42a3-8313-585da384a1b3"/>
</details>

Note that you can always see the summary by clicking on the **Package Lint** on the left, which is a lot more usable *and* contains the rendered changelog:

![afbeelding](https://github.com/getsolus/packages/assets/5798032/59ac6f8e-8a34-47d1-b8ea-129a4fd06d25)

**Comment by TraceyC77** [comment]
I think I found the culprit on my end. I went to the PR you linked, and noticed my javascript blocker had some things blocked. After enabling those, I was able to see the detail in your PR. I'll re-test this as soon as I have something else to push.

**Comment by TraceyC77** [comment]
I haven't seen this since my last comment. Closing.
