### ISSUE TITLE
no wired internet (T10556)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#268]
<div dir="rtl"><b>Rinus&nbsp;Verhelst</b>&nbsp;(<em>&#35;rinus</em>),&nbsp;2023-06-14&nbsp;19:05:10&nbsp;UTC</div><br/>

Hello all,
from kernel 6. i no longer have wired internet, but wifi.
with kernel 5.13 i do have wired internet and also wifi.
I would like wired internet
THE is SolusMATE
kernel 6.3.6
network card Realtec RTL 8111/8168/8411 PCI Express Gigabit Ethernet

**Comment by TraceyC77** [comment]
The user indicated in the forums that the problem is now resolved, closing.

https://discuss.getsol.us/d/9344-realtec-rtl-8111/20

Ik heb de update uitgevoerd en weer gekeken, nu heb ik ook met de current kernel 6.5.3-256 bekabeld internet.
Allemaal hartelijk bedankt voor uw hulp.
Dit probleem is nu opgelost.
