### ISSUE TITLE
Package request: wl-clipboard (T10598)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#273]
<div dir="rtl"><b>Sebastian&nbsp;Spree</b>&nbsp;(<em>&#35;Sebastian</em>),&nbsp;2023-07-29&nbsp;11:18:53&nbsp;UTC</div><br/>

wl-clipboard

https://github.com/bugaevc/wl-clipboard

This project implements two command-line Wayland clipboard utilities, wl-copy and wl-paste, that let you easily copy data between the clipboard and Unix pipes, sockets, files and so on.

pass password manager does rely on wl-clipboard in a Gnome Wayland session

Is it open source? Yes
https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v2.2.0.tar.gz

**Comment by sebo505** [comment]
It is still the case pass (password-store) fails to copy password to clipboard in wayland session due to lack of wl-clipboard.
In #pass channel on Libera.Chat I was told that if we don't want to include wl-clipboard, another option would be to patch pass to use another clipboard manager instead. I was told such a patch would already exist somewhere in [pass mailing list archive](https://lists.zx2c4.com/pipermail/password-store/)
Would it be an option for Solus to adopt such a patch?

**Comment by EbonJaeger** [comment]
The above-mentioned dependencies are both optional. Since this is a runtime dependency of included software, this probably should have been implicitly accepted.
