### ISSUE TITLE
Thunderbolt audio not working (T6365)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#33]
<div dir="rtl"><b>TraceyC</b>&nbsp;(<em>&#35;TClark77</em>),&nbsp;2018-05-09&nbsp;00:22:41&nbsp;UTC</div><br/>

**Setup**: Lenovo Carbon X1 connected via USB C to a Thunderbolt dock.
The dock is connected via DisplayPort cable to a monitor which has audio out 
The speakers work in Windows and Ubuntu Budgie
USB headphones that are connected to a USB hub connected to the monitor work
The speakers are detected in all OS's and distros I have tried, and shown in the Audo Control Panel (They are greyed out in Kubuntu)
Ubuntu Budgie only plays sound through the external speakers if I set the Built In Audio to HDMI 4

The speakers are detected but play no sound in Solus Plasma and NetRunner Rolling (Arch). This is even after switching audio out to The ThinkPad Dock and trying various settings in the drop downs for the "Built-in Audio" and "ThinkPad Thunderbot 3 Dock USB Audio"

**Comment by TraceyC77** [comment]
Since I opened this issue, my hardware has changed a bit, as well as the setup. Audio is still being carried from the laptop via Thunderbolt to a USB hub
Dell XPS 7910 laptop -> Thunderbolt dock -> USB Hub -> Speakers / keyboard / mouse etc
At this time all sound devices, including the speakers, are detected and play sound. Everything is working as intended.
