### ISSUE TITLE
Merkuro Mail does not create an app menu entry

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#4029]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

After installing Merkuro Mail, I don't have an entry for it in the app menu

### Steps to reproduce

1. Use Discover to install Merkuro Mail
2. Open the Kickoff / App menu (or krunner with Alt-Space)
3. Type in Me

### Expected result

All 3 Merkuro apps are listed since I installed all 3

### Actual result

Merkuro Calendar and Contacts are listed
Merkuro Mail is not listed

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.3
Kernel Version: 6.10.13-304.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

I can launch the app from Discover

**Comment by androidnisse** [comment]
In the desktop file for the Mail part it is set to not show up: `NoDisplay=true` So the question is should this line be patched and removed or not? According to https://apps.kde.org/en-gb/merkuro.mail/ it is in beta and can only read emails.

**Comment by ReillyBrogan** [comment]
It looks like it's an intentional decision to cause it not to show up: https://invent.kde.org/pim/merkuro/-/commit/77c1dd6d18019498c1293304cb9eb3bfc3e4dd7d, most likely because while they build it by default for easy testing they don't yet deem it ready for public use. If upstream considers this not ready for public consumption I don't see any reason to override them, especially since it's easy to launch it from the terminal or edit the .desktop file to make it show up again.
