### ISSUE TITLE
After weekly update, Bluetooth is disabled.  

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#416]
### Summary

I use a multi-device Bluetooth mouse and keyboard that I can connect to my laptop, my media computer across the
room, or my smartphone for SMS texting.  Several weekly updates ago, after I rebooted my laptop, neither the mouse
nor the keyboard had any effect.  Sometimes a reboot works differently than a shutdown and restart, so I tried that with
the same results.

This had never happened before, and at first I didn't realize it was a Bluetooth issue.  All I knew was that I couldn't do
anything at all with my laptop, and restarting it did nothing to help.  So I decided to reinstall the OS.  Installing Solus was
fast, but installing and configuring everything else took the better part of a day.  But I was back in business, and I'd made
some small improvements this time.
  
The next week, the same thing happened.  This time, it occurred to me to try using another mouse, so I found a wireless
mouse, plugged in its dongle, and indeed that mouse was active.  So I checked the Bluetooth settinngs in the System
Settings, and found there was no need to re-pair the mouse and keyboard -- Bluetooth was simply disabled altogether.
Clicking to turn it back on solved everything.  The peripherals even reconnected themselves automatically.

This has now happened after several subsequent weekly updates, and I've re-enabled Bluetooth that way.  It's annoying,
but not difficult to do, so this is a low-priority issue at most.

### Steps to reproduce

No special steps are needed.  What I've described has been the result of several ordinary weekly updates.

### Expected result

Always before, the mouse and keyboard have been active following an update and reboot.  No changes were needed to the Bluetooth settings to re-activate them.

### Actual result

Please see my issue description above for more details.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

Sorry, I have no idea where to find the _About this system_ information you're requesting.  The following is from the Plasma System Settings.

![image](https://github.com/getsolus/packages/assets/6805994/a9762db2-bec6-4db0-ad49-2ac916e44452)

**Comment by ReillyBrogan** [comment]
Oh, I know this one actually. It's a bug in bluedevil (the Plasma bluetooth integration) that caused the bluedevil config file to be left in an invalid state which causes issues like this. You can do the following to fix it:
```
rm ~/.config/bluedevilglobalrc
```
And then reboot and when you get logged back in re-enable bluetooth in the settings and it should be fine again. I _think_ they fixed the bug upstream so it won't happen again but if you re-install your system and then update it to the latest you'll probably see it again since it happens on updates.

**Comment by ReillyBrogan** [comment]
I found the upstream bug report: https://bugs.kde.org/show_bug.cgi?id=469119

I was a bit wrong about it, based on my understanding of Plasma this is probably caused by the way that Plasma Wayland exits the session. It does so very ungracefully which causes the kded5 daemon to get killed before it can update the settings on file on disk. The result is that you choosing "enable bluetooth" is not saved and persisted to your next login. This should be improved by e1354bbe8271ade1a842da0fac24657695479413, let me know if it isn't.

**Comment by WetGeek** [comment]
Thanks, Reilly.  Because the workaround is so trivial, I don't mind just waiting for the inevitable fix to show up.  If I have to re-enable Bluetooth manually two or three more times, I won't mind.  Since it's a known issue upstream, I'm sure it won't be long.  The first update that doesn't _require_ me to use the workaround, I'll let you know.

Now, if we could finally figure out the problem wherein taking a Virtual Box VM to full-screen during a Wayland session locks everything up, I'll finally be totally happy with Wayland.  I think I'll file a big report for that one, too.  It won't hurt to have someone look into it.
