### ISSUE TITLE
leafpad: needs up to 30 seconds to start

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#540]
### Summary

leafpad text editor for some reason starts with a delay of up to 30 seconds. This behaviour appeared first maybe 10 weeks ago. Before that, it used to start extremely fast.

### Steps to reproduce

run leafpad from terminal or via your favourite way to start an app in your DE

### Expected result

leafpad should startup right away

### Actual result

leafpad starts with a delay of up to 30 seconds

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

Hewlett-Packard HP EliteBook 6930p
Solus 4.4 Harmony
GNOME 44.3
X11
Kernel Linux 6.5.5-258.current

**Comment by sheepman4267** [comment]
@sebo505 Would you mind doing updates and testing this again to see if your experience is the same as mine? I was able to reproduce this a week or so ago, but now I can't get it to take forever when launching from the terminal. Right now, I only appear to have this issue when launching Leafpad from the GNOME Shell launcher.

I have a hunch that this is caused by some sort of incompatibility between Leafpad and GNOME's SSH keyring, but I can't be sure as I'm not certain I'm reproducing this correctly. 

When you have a moment, would you please;

1. Make sure your system is up to date (`eopkg up` or via Software Center)
2. Open leafpad by running `leafpad` in a terminal
3. Close leafpad, then open it by running `gtk-launch leafpad` in a terminal
4. Close leafpad, then open it by searching in the GNOME Shell launcher

On my system, steps 2 and 3 result in leafpad opening very quickly, while step 4 takes an unreasonably long time. If you get the same results, I'll go back to troubleshooting- if not, I'll try again to reproduce the slow launching behavior from a terminal.

Thanks!

**Comment by sebo505** [comment]
@sheepman4267 I observe something totally different and very inconsistent. 
running leafpad from terminal, leafpad starts with a delay of about 25 seconds. every time. except the first time. first time it starts right away, sometimes.
running leafpad with gtk-launch, it starts always with a delay of about 25 seconds. (though I haven't tried to run leafpad via gtk-launch before running it via terminal)
running leafpad via searching in the GNOME Shell launcher, leafpad starts right away roughly every second time: like I run it via searching in the GNOME Shell launcher, leafpad starts right away. I close it immediately an rerun it via searching in the GNOME Shell launcher, it starts with long delay.
I close it, it starts right away if i try immediately again.
I figured that if wait roughly 20 sec before rerunning it via searching in the GNOME Shell launcher, it starts right away often, but nor every time.
I also have encountered that I could open and close it like 6 times in a row without delay, and then the 7th time it startet again with a long delay.

Unfortunately I can't narrow this behavoiur down to something particular.

**Comment by ermo** [comment]
@joebonrichie Can you reproduce this behaviour?

**Comment by sebo505** [comment]
I performed some testing after todays sync. The issue seems to be resolved. Leafpad now starts right away no matter if I start it via leafpad, gtk-launch leafpad or by searching in the GNOME Shell launcher.

**Comment by ReillyBrogan** [comment]
Hmmm I just tested it on my VM and this still seems to be happening for me.

**Comment by sebo505** [comment]
Strange. I booted in another hard disk where I have a fresh Budgie install. Installed leafpad there. Starts with a delay no matter how I start it.
Back on my GNOME hard disk: leafpad starts just wine under X11 no matter if I run it directly in terminal, with gtk-launch or via via searching in the GNOME Shell launcher.
But under Wayland there is an delay if I start via searching in the GNOME Shell launcher.
