### ISSUE TITLE
opendoas

### ISSUE THREAD

**Issue by hertz-hwang** [getsolus/packages#557]
### Homepage

https://github.com/Duncaen/OpenDoas

### Why should this be included in the repository?

A portable fork of the OpenBSD `doas` command. It's common in other popular linux distros, but missing in Solus official repo.

### Are we allowed to redistribute it?

ISC

### Who and how many users do you anticipate will use this software?

Sorry I don't know how many users will use it, but it is a lightly replacement of "sudo".

### Link to source archive file

https://github.com/Duncaen/OpenDoas/releases/download/v6.8.2/opendoas-6.8.2.tar.gz

**Comment by ReillyBrogan** [comment]
So we actually evaluated opendoas on SerpentOS as a potential sudo replacement back before SerpentOS pivoted to being an upstream for Solus. I was actually the person who packaged opendoas, so I'm very aware of the limitations of it. We ultimately went back to sudo for a few reasons:
- opendoas on Linux is minimally maintained. While sudo has a much larger codebase it also has more people maintaining it, working on detecting security vulnerabilities (scanning, fuzzing, etc), and generally fixing bugs. Having a smaller codebase does not necessarily mean that opendoas is more secure, just that it has a smaller codebase.
- Even if you create a symlink at `/usr/bin/sudo` to `doas` it's _just_ different enough that users get confused with the differences. `sudo` is ubiquitous on Linux distributions and a given Linux user will know exactly what to expect when they use it.

Unfortunately I'm going to have to reject this package request because we just don't need another tool that duplicates sudo in the Solus repos when we already have sudo. Adding doas won't really benefit our users in any way since sudo is still going to be installed and can't be removed since it's part of system.base.

Side note, I'm personally keeping watch on [sudo-rs](https://github.com/memorysafety/sudo-rs) as the future replacement of sudo. It's not mature enough yet IMO, but it looks like it has the momentum behind it to reach that point eventually.
