### ISSUE TITLE
Update kdenlive to 23.08.02

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#724]
### Name

kdenlive

### Version

23.08.02

### Link to the release notes or announcement.

https://kdenlive.org/en/2023/10/kdenlive-23-08-2-released/

**Comment by ReillyBrogan** [comment]
kdenlive is part of kde gear and so is updated whenever we update the entire kde gear stack. We don't update kde gear applications independently, and since we (the Solus plasma maintainers) already know that we need to update to kde gear 23.08.2 I'm going to close this since we don't really need that reminder (if that makes sense).
