### ISSUE TITLE
Gnome Web / webkit: enable MPRIS support

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#883]
### Summary

Playing audio/video with GNOME Web, the audio source is not shown in GNOME's media control (super+v).
I have found this [post](https://gitlab.gnome.org/GNOME/epiphany/-/issues/1453) that states that for MPRIS support webkit must be build with -DENABLE_EXPERIMENTAL_FEATURES=ON
Would you consider doing so?

### Steps to reproduce

open GNOME Web
play audio/video stream
press super+v

### Expected result

audio source should appear in MPRIS media control

### Actual result

audio does not appear in MPRIS media control

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

# Systemdetailsbericht
---

## Berichtdetails
- **Erstellungsdatum:**                            2023-11-24 20:51:40

## Hardware Information:
- **Hardware-Modell:**                             Hewlett-Packard HP EliteBook 6930p
- **Speicher:**                                    8,0 GiB
- **Prozessor:**                                   Intel® Core™2 Duo T9550  × 2
- **Grafik:**                                      AMD RV620
- **Festplattenkapazität:**                        500,1 GB

## Software Information:
- **Firmware-Version:**                            68PCD Ver. F.16
- **Name des Betriebssystems:**                    Solus 4.4 Harmony
- **Betriebssystem-Build:**                        (null)
- **Betriebssystem-Typ:**                          64-bit
- **GNOME-Version:**                               Nicht verfügbar
- **Fenstermanager:**                              X11
- **Kernel-Version:**                              Linux 6.5.11-263.current

**Comment by ReillyBrogan** [comment]
Thanks for the issue report @sebo505!

Looks like the feature was enabled by default briefly but then disabled because it has severe issues: https://bugs.webkit.org/show_bug.cgi?id=247527. Given that I'm inclined to not enable it in our libwebkitgtk builds as the lack of this feature is hardly a dealbreaker there (you can always use a browser that supports MPRIS just for that). Going to close this for now since as an upstream issue it would just clutter our tracker, but feel free to re-open once the upstream bug report is closed.
